
import time
from productsuyaun.public import login1
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
DL=login1.Test_Denglu()

class XZCP():
     def plscfwm(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量生成防伪码").click()
         time.sleep(2)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(1) > div:nth-child(2) > input:nth-child(1)")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(1) > div:nth-child(2) > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(1) > div:nth-child(2) > input:nth-child(1)").send_keys("202011102379553")
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)").send_keys("8")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(3) > div:nth-child(2) > input:nth-child(1)").send_keys("mz92")
         time.sleep(5)
         Select(DL.driver.find_element_by_css_selector("#code_type")).select_by_index(3)
         Select(DL.driver.find_element_by_css_selector("#txm_type")).select_by_index(1)
         DL.driver.find_element_by_css_selector("div.col-sm-2:nth-child(4) > input:nth-child(1)")
         DL.driver.find_element_by_css_selector("div.col-sm-2:nth-child(4) > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector("div.col-sm-2:nth-child(4) > input:nth-child(1)").send_keys("6")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(6) > div:nth-child(2) > input:nth-child(1)").send_keys("10")
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(7) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector(".has-next > div:nth-child(2) > div:nth-child(17)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(8) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(8) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(16)").click()
         time.sleep(5)
         Select(DL.driver.find_element_by_css_selector("#qiyong")).select_by_index(1)
         DL.driver.find_element_by_css_selector("#tj").click()

     def plscfwm_FAN1(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量生成防伪码").click()
         time.sleep(2)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(1) > div:nth-child(2) > input:nth-child(1)")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(1) > div:nth-child(2) > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(1) > div:nth-child(2) > input:nth-child(1)").send_keys(Keys.SPACE)
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)").send_keys("8")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(3) > div:nth-child(2) > input:nth-child(1)").send_keys("mz92")
         time.sleep(5)
         Select(DL.driver.find_element_by_css_selector("#code_type")).select_by_index(3)
         Select(DL.driver.find_element_by_css_selector("#txm_type")).select_by_index(1)
         DL.driver.find_element_by_css_selector("div.col-sm-2:nth-child(4) > input:nth-child(1)")
         DL.driver.find_element_by_css_selector("div.col-sm-2:nth-child(4) > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector("div.col-sm-2:nth-child(4) > input:nth-child(1)").send_keys("6")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(6) > div:nth-child(2) > input:nth-child(1)").send_keys(Keys.SPACE)
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(7) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector(".has-next > div:nth-child(2) > div:nth-child(17)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(8) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(8) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(16)").click()
         time.sleep(5)
         Select(DL.driver.find_element_by_css_selector("#qiyong")).select_by_index(1)
         DL.driver.find_element_by_css_selector("#tj").click()

     def dgscfwm(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("单个生成防伪码").click()
         time.sleep(2)
         DL.driver.find_element_by_css_selector(".col-sm-3 > input:nth-child(1)")
         DL.driver.find_element_by_css_selector(".col-sm-3 > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector(".col-sm-3 > input:nth-child(1)").send_keys("202011102379553")
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)").send_keys("MZLOVEGIRL")
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(3) > div:nth-child(2) > input:nth-child(1)")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(3) > div:nth-child(2) > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(3) > div:nth-child(2) > input:nth-child(1)").send_keys("19843152")
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(4) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.searchable-select-item:nth-child(23)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(5) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(5) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(11)").click()
         time.sleep(5)
         Select(DL.driver.find_element_by_css_selector("#qiyong")).select_by_index(1)
         DL.driver.find_element_by_css_selector(".btn").click()

     def dgscfwm_FAN1(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("单个生成防伪码").click()
         time.sleep(2)
         DL.driver.find_element_by_css_selector(".col-sm-3 > input:nth-child(1)")
         DL.driver.find_element_by_css_selector(".col-sm-3 > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector(".col-sm-3 > input:nth-child(1)").send_keys(Keys.SPACE)
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(2) > div:nth-child(2) > input:nth-child(1)").send_keys(Keys.SPACE)
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(3) > div:nth-child(2) > input:nth-child(1)")
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(3) > div:nth-child(2) > input:nth-child(1)").clear()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(3) > div:nth-child(2) > input:nth-child(1)").send_keys(Keys.SPACE)
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(4) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.searchable-select-item:nth-child(23)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(5) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.form-group:nth-child(5) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(11)").click()
         time.sleep(5)
         Select(DL.driver.find_element_by_css_selector("#qiyong")).select_by_index(1)
         DL.driver.find_element_by_css_selector(".btn").click()

     def plxgfwm(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量修改防伪码").click()
         time.sleep(2)
         DL.driver.find_element_by_css_selector("#txm").send_keys("19843152")
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(16)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(5)").click()
         time.sleep(5)

     def plxgfwm_FAN1(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量修改防伪码").click()
         time.sleep(2)
         DL.driver.find_element_by_css_selector("#txm").send_keys(Keys.SPACE)
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(16)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(5)").click()
         time.sleep(5)

     def plxgfwm_FAN2(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量修改防伪码").click()
         time.sleep(2)
         DL.driver.find_element_by_css_selector("#txm").send_keys("23794355")
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(16)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(5)").click()
         time.sleep(5)

     def plxgfwm_ID(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量修改防伪码").click()
         time.sleep(2)
         target_elem = DL.driver.find_element_by_css_selector("div.row:nth-child(2) > div:nth-child(1) > section:nth-child(1) > header:nth-child(1) > h3:nth-child(1)")
         DL.driver.execute_script("return arguments[0].scrollIntoView();", target_elem)
         DL.driver.find_element_by_css_selector("div.col-sm-2:nth-child(2) > input:nth-child(1)").send_keys("m")
         DL.driver.find_element_by_xpath("/html/body/section/section/section/div[2]/div/section/div/form/div[1]/div[2]/input").send_keys("Z")
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(2) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(2) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(10)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(2) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(2) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(11)").click()
         time.sleep(5)

     def plxgfwm_ID_FAN(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量修改防伪码").click()
         time.sleep(2)
         target_elem = DL.driver.find_element_by_css_selector("div.row:nth-child(2) > div:nth-child(1) > section:nth-child(1) > header:nth-child(1) > h3:nth-child(1)")
         DL.driver.execute_script("return arguments[0].scrollIntoView();", target_elem)
         DL.driver.find_element_by_css_selector("div.col-sm-2:nth-child(2) > input:nth-child(1)").send_keys(Keys.SPACE)
         DL.driver.find_element_by_xpath("/html/body/section/section/section/div[2]/div/section/div/form/div[1]/div[2]/input").send_keys(Keys.SPACE)
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(2) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(2) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(10)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(2) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(2) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(11)").click()
         time.sleep(5)

     def plxgfwm_pcpl(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量修改防伪码").click()
         time.sleep(2)
         target_elem = DL.driver.find_element_by_css_selector("div.row:nth-child(3) > div:nth-child(1) > section:nth-child(1) > header:nth-child(1) > h3:nth-child(1)")
         DL.driver.execute_script("return arguments[0].scrollIntoView();", target_elem)
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(3) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(3) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(6)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(3) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(3) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(10)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(3) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(3) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(5)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(3) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(4) > div:nth-child(1) > button:nth-child(1)").click()

     def plxgfwm_pl(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量修改防伪码").click()
         time.sleep(2)
         target_elem = DL.driver.find_element_by_css_selector("div.row:nth-child(4) > div:nth-child(1) > section:nth-child(1) > header:nth-child(1) > h3:nth-child(1)")
         DL.driver.execute_script("return arguments[0].scrollIntoView();", target_elem)
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(4) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(4) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(10)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(4) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_xpath("/html/body/section/section/section/div[4]/div/section/div/form/div[2]/div[1]/div/div[2]/div/div[2]/div[2]").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(4) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(1) > button:nth-child(1)").click()

     def plxgfwm_date(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量修改防伪码").click()
         time.sleep(2)
         DL.driver.find_element_by_css_selector("div.row:nth-child(5) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(5) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         time.sleep(2)
         DL.driver.find_element_by_css_selector("div.row:nth-child(5) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(5) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(17)").click()
         time.sleep(5)
         DL.driver.find_element_by_css_selector("div.row:nth-child(5) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector("div.row:nth-child(5) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(10)").click()
         time.sleep(2)

     def plscfwm1_pc(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量删除防伪码").click()
         time.sleep(2)
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_xpath("/html/body/section/section/section/div[1]/div/section/div/form/div[1]/div[1]/div/div[2]/div/div[2]/div[6]").click()
         time.sleep(2)
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(1) > button:nth-child(1)").click()
         time.sleep(4)

     def plscfwm1_pl(self):
         DL.driver.find_element_by_css_selector("a.active > span:nth-child(2)").click()
         DL.driver.find_element_by_link_text("批量删除防伪码").click()
         time.sleep(2)
         target_elem = DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > header:nth-child(1) > h3:nth-child(1)")
         DL.driver.execute_script("return arguments[0].scrollIntoView();", target_elem)
         time.sleep(3)
         DL.driver.find_element_by_css_selector("div.row:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)").click()
         DL.driver.find_element_by_css_selector(".row:nth-child(3) .panel-body").click()
         time.sleep(3)














